import type { Metadata } from "next";
<<<<<<< HEAD
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
=======
import "./globals.css";

export const metadata: Metadata = {
  title: "Memex — AML Intelligence Terminal",
  description: "Glass Box visualizer for autonomous RL agent operating system. Anti-Money Laundering investigation platform.",
  keywords: ["AML", "Anti-Money Laundering", "Reinforcement Learning", "1MDB", "Investigation"],
>>>>>>> 85b18b358464e3203bde643fa27d6209bdda40c2
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
=======
    <html lang="en" className="dark">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@300;400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="bg-bg text-text min-h-screen antialiased" style={{ fontFamily: "'JetBrains Mono', monospace" }}>
        {children}
      </body>
>>>>>>> 85b18b358464e3203bde643fa27d6209bdda40c2
    </html>
  );
}
